0 0 * * * /opt/aws/automatition/start/ad/start-ad-00.sh
0 1 * * * /opt/aws/automatition/start/ad/start-ad-01.sh
0 2 * * * /opt/aws/automatition/start/ad/start-ad-02.sh
0 3 * * * /opt/aws/automatition/start/ad/start-ad-03.sh
0 4 * * * /opt/aws/automatition/start/ad/start-ad-04.sh
0 5 * * * /opt/aws/automatition/start/ad/start-ad-05.sh
0 6 * * * /opt/aws/automatition/start/ad/start-ad-06.sh
0 7 * * * /opt/aws/automatition/start/ad/start-ad-07.sh
0 8 * * * /opt/aws/automatition/start/ad/start-ad-08.sh
0 9 * * * /opt/aws/automatition/start/ad/start-ad-09.sh
0 10 * * * /opt/aws/automatition/start/ad/start-ad-10.sh
0 11 * * * /opt/aws/automatition/start/ad/start-ad-11.sh
0 12 * * * /opt/aws/automatition/start/ad/start-ad-12.sh
0 13 * * * /opt/aws/automatition/start/ad/start-ad-13.sh
0 14 * * * /opt/aws/automatition/start/ad/start-ad-14.sh
0 15 * * * /opt/aws/automatition/start/ad/start-ad-15.sh
0 16 * * * /opt/aws/automatition/start/ad/start-ad-16.sh
0 17 * * * /opt/aws/automatition/start/ad/start-ad-17.sh
0 18 * * * /opt/aws/automatition/start/ad/start-ad-18.sh
0 19 * * * /opt/aws/automatition/start/ad/start-ad-19.sh
0 20 * * * /opt/aws/automatition/start/ad/start-ad-20.sh
0 21 * * * /opt/aws/automatition/start/ad/start-ad-21.sh
0 22 * * * /opt/aws/automatition/start/ad/start-ad-22.sh
0 23 * * * /opt/aws/automatition/start/ad/start-ad-23.sh
0 0 * * 1-5 /opt/aws/automatition/start/wd/start-wd-00.sh
0 1 * * 1-5 /opt/aws/automatition/start/wd/start-wd-01.sh
0 2 * * 1-5 /opt/aws/automatition/start/wd/start-wd-02.sh
0 3 * * 1-5 /opt/aws/automatition/start/wd/start-wd-03.sh
0 4 * * 1-5 /opt/aws/automatition/start/wd/start-wd-04.sh
0 5 * * 1-5 /opt/aws/automatition/start/wd/start-wd-05.sh
0 6 * * 1-5 /opt/aws/automatition/start/wd/start-wd-06.sh
0 7 * * 1-5 /opt/aws/automatition/start/wd/start-wd-07.sh
0 8 * * 1-5 /opt/aws/automatition/start/wd/start-wd-08.sh
0 9 * * 1-5 /opt/aws/automatition/start/wd/start-wd-09.sh
0 10 * * 1-5 /opt/aws/automatition/start/wd/start-wd-10.sh
0 11 * * 1-5 /opt/aws/automatition/start/wd/start-wd-11.sh
0 12 * * 1-5 /opt/aws/automatition/start/wd/start-wd-12.sh
0 13 * * 1-5 /opt/aws/automatition/start/wd/start-wd-13.sh
0 14 * * 1-5 /opt/aws/automatition/start/wd/start-wd-14.sh
0 15 * * 1-5 /opt/aws/automatition/start/wd/start-wd-15.sh
0 16 * * 1-5 /opt/aws/automatition/start/wd/start-wd-16.sh
0 17 * * 1-5 /opt/aws/automatition/start/wd/start-wd-17.sh
0 18 * * 1-5 /opt/aws/automatition/start/wd/start-wd-18.sh
0 19 * * 1-5 /opt/aws/automatition/start/wd/start-wd-19.sh
0 20 * * 1-5 /opt/aws/automatition/start/wd/start-wd-20.sh
0 21 * * 1-5 /opt/aws/automatition/start/wd/start-wd-21.sh
0 22 * * 1-5 /opt/aws/automatition/start/wd/start-wd-22.sh
0 23 * * 1-5 /opt/aws/automatition/start/wd/start-wd-23.sh
0 0 * * * /opt/aws/automatition/stop/ad/stop-ad-00.sh
0 1 * * * /opt/aws/automatition/stop/ad/stop-ad-01.sh
0 2 * * * /opt/aws/automatition/stop/ad/stop-ad-02.sh
0 3 * * * /opt/aws/automatition/stop/ad/stop-ad-03.sh
0 4 * * * /opt/aws/automatition/stop/ad/stop-ad-04.sh
0 5 * * * /opt/aws/automatition/stop/ad/stop-ad-05.sh
0 6 * * * /opt/aws/automatition/stop/ad/stop-ad-06.sh
0 7 * * * /opt/aws/automatition/stop/ad/stop-ad-07.sh
0 8 * * * /opt/aws/automatition/stop/ad/stop-ad-08.sh
0 9 * * * /opt/aws/automatition/stop/ad/stop-ad-09.sh
0 10 * * * /opt/aws/automatition/stop/ad/stop-ad-10.sh
0 11 * * * /opt/aws/automatition/stop/ad/stop-ad-11.sh
0 12 * * * /opt/aws/automatition/stop/ad/stop-ad-12.sh
0 13 * * * /opt/aws/automatition/stop/ad/stop-ad-13.sh
0 14 * * * /opt/aws/automatition/stop/ad/stop-ad-14.sh
0 15 * * * /opt/aws/automatition/stop/ad/stop-ad-15.sh
0 16 * * * /opt/aws/automatition/stop/ad/stop-ad-16.sh
0 17 * * * /opt/aws/automatition/stop/ad/stop-ad-17.sh
0 18 * * * /opt/aws/automatition/stop/ad/stop-ad-18.sh
0 19 * * * /opt/aws/automatition/stop/ad/stop-ad-19.sh
0 20 * * * /opt/aws/automatition/stop/ad/stop-ad-20.sh
0 21 * * * /opt/aws/automatition/stop/ad/stop-ad-21.sh
0 22 * * * /opt/aws/automatition/stop/ad/stop-ad-22.sh
0 23 * * * /opt/aws/automatition/stop/ad/stop-ad-23.sh
0 0 * * 1-5 /opt/aws/automatition/stop/wd/stop-wd-00.sh
0 1 * * 1-5 /opt/aws/automatition/stop/wd/stop-wd-01.sh
0 2 * * 1-5 /opt/aws/automatition/stop/wd/stop-wd-02.sh
0 3 * * 1-5 /opt/aws/automatition/stop/wd/stop-wd-03.sh
0 4 * * 1-5 /opt/aws/automatition/stop/wd/stop-wd-04.sh
0 5 * * 1-5 /opt/aws/automatition/stop/wd/stop-wd-05.sh
0 6 * * 1-5 /opt/aws/automatition/stop/wd/stop-wd-06.sh
0 7 * * 1-5 /opt/aws/automatition/stop/wd/stop-wd-07.sh
0 8 * * 1-5 /opt/aws/automatition/stop/wd/stop-wd-08.sh
0 9 * * 1-5 /opt/aws/automatition/stop/wd/stop-wd-09.sh
0 10 * * 1-5 /opt/aws/automatition/stop/wd/stop-wd-10.sh
0 11 * * 1-5 /opt/aws/automatition/stop/wd/stop-wd-11.sh
0 12 * * 1-5 /opt/aws/automatition/stop/wd/stop-wd-12.sh
0 13 * * 1-5 /opt/aws/automatition/stop/wd/stop-wd-13.sh
0 14 * * 1-5 /opt/aws/automatition/stop/wd/stop-wd-14.sh
0 15 * * 1-5 /opt/aws/automatition/stop/wd/stop-wd-15.sh
0 16 * * 1-5 /opt/aws/automatition/stop/wd/stop-wd-16.sh
0 17 * * 1-5 /opt/aws/automatition/stop/wd/stop-wd-17.sh
0 18 * * 1-5 /opt/aws/automatition/stop/wd/stop-wd-18.sh
0 19 * * 1-5 /opt/aws/automatition/stop/wd/stop-wd-19.sh
0 20 * * 1-5 /opt/aws/automatition/stop/wd/stop-wd-20.sh
0 21 * * 1-5 /opt/aws/automatition/stop/wd/stop-wd-21.sh
0 22 * * 1-5 /opt/aws/automatition/stop/wd/stop-wd-22.sh
0 23 * * 1-5 /opt/aws/automatition/stop/wd/stop-wd-23.sh
0 0 * * * /opt/aws/automatition/reboot/ad/reboot-ad-00.sh
0 1 * * * /opt/aws/automatition/reboot/ad/reboot-ad-01.sh
0 2 * * * /opt/aws/automatition/reboot/ad/reboot-ad-02.sh
0 3 * * * /opt/aws/automatition/reboot/ad/reboot-ad-03.sh
0 4 * * * /opt/aws/automatition/reboot/ad/reboot-ad-04.sh
0 5 * * * /opt/aws/automatition/reboot/ad/reboot-ad-05.sh
0 6 * * * /opt/aws/automatition/reboot/ad/reboot-ad-06.sh
0 7 * * * /opt/aws/automatition/reboot/ad/reboot-ad-07.sh
0 8 * * * /opt/aws/automatition/reboot/ad/reboot-ad-08.sh
0 9 * * * /opt/aws/automatition/reboot/ad/reboot-ad-09.sh
0 10 * * * /opt/aws/automatition/reboot/ad/reboot-ad-10.sh
0 11 * * * /opt/aws/automatition/reboot/ad/reboot-ad-11.sh
0 12 * * * /opt/aws/automatition/reboot/ad/reboot-ad-12.sh
0 13 * * * /opt/aws/automatition/reboot/ad/reboot-ad-13.sh
0 14 * * * /opt/aws/automatition/reboot/ad/reboot-ad-14.sh
0 15 * * * /opt/aws/automatition/reboot/ad/reboot-ad-15.sh
0 16 * * * /opt/aws/automatition/reboot/ad/reboot-ad-16.sh
0 17 * * * /opt/aws/automatition/reboot/ad/reboot-ad-17.sh
0 18 * * * /opt/aws/automatition/reboot/ad/reboot-ad-18.sh
0 19 * * * /opt/aws/automatition/reboot/ad/reboot-ad-19.sh
0 20 * * * /opt/aws/automatition/reboot/ad/reboot-ad-20.sh
0 21 * * * /opt/aws/automatition/reboot/ad/reboot-ad-21.sh
0 22 * * * /opt/aws/automatition/reboot/ad/reboot-ad-22.sh
0 23 * * * /opt/aws/automatition/reboot/ad/reboot-ad-23.sh
0 0 * * 1-5 /opt/aws/automatition/reboot/wd/reboot-wd-00.sh
0 1 * * 1-5 /opt/aws/automatition/reboot/wd/reboot-wd-01.sh
0 2 * * 1-5 /opt/aws/automatition/reboot/wd/reboot-wd-02.sh
0 3 * * 1-5 /opt/aws/automatition/reboot/wd/reboot-wd-03.sh
0 4 * * 1-5 /opt/aws/automatition/reboot/wd/reboot-wd-04.sh
0 5 * * 1-5 /opt/aws/automatition/reboot/wd/reboot-wd-05.sh
0 6 * * 1-5 /opt/aws/automatition/reboot/wd/reboot-wd-06.sh
0 7 * * 1-5 /opt/aws/automatition/reboot/wd/reboot-wd-07.sh
0 8 * * 1-5 /opt/aws/automatition/reboot/wd/reboot-wd-08.sh
0 9 * * 1-5 /opt/aws/automatition/reboot/wd/reboot-wd-09.sh
0 10 * * 1-5 /opt/aws/automatition/reboot/wd/reboot-wd-10.sh
0 11 * * 1-5 /opt/aws/automatition/reboot/wd/reboot-wd-11.sh
0 12 * * 1-5 /opt/aws/automatition/reboot/wd/reboot-wd-12.sh
0 13 * * 1-5 /opt/aws/automatition/reboot/wd/reboot-wd-13.sh
0 14 * * 1-5 /opt/aws/automatition/reboot/wd/reboot-wd-14.sh
0 15 * * 1-5 /opt/aws/automatition/reboot/wd/reboot-wd-15.sh
0 16 * * 1-5 /opt/aws/automatition/reboot/wd/reboot-wd-16.sh
0 17 * * 1-5 /opt/aws/automatition/reboot/wd/reboot-wd-17.sh
0 18 * * 1-5 /opt/aws/automatition/reboot/wd/reboot-wd-18.sh
0 19 * * 1-5 /opt/aws/automatition/reboot/wd/reboot-wd-19.sh
0 20 * * 1-5 /opt/aws/automatition/reboot/wd/reboot-wd-20.sh
0 21 * * 1-5 /opt/aws/automatition/reboot/wd/reboot-wd-21.sh
0 22 * * 1-5 /opt/aws/automatition/reboot/wd/reboot-wd-22.sh
0 23 * * 1-5 /opt/aws/automatition/reboot/wd/reboot-wd-23.sh
